### ISSUE TITLE
Inadvertant termination of ALL ec2 instances in region

### ISSUE THREAD

**Issue by jthomaskerr** [seek-oss/aec#373]
I am using aec via a bash script, which because of a configuration error executed `aec ec2 terminate "$instanceId"` with an empty `$instanceId`.

This had the rather unfortunate effect of terminating *all* of the ec2 instances visible to my role in the selected region. Looking at `ec2.py` it looks like the empty `name` argument was passed through to describe which happily returned all of the instances which where then deleted.

I think that terminate (and probably start and stop) should probably refuse to operate on more than one instance at a time, or alternatively guard against an empty name filter.

**Comment by tekumara** [comment]
yikes! 😬 thanks for raising this, I agree this is worth guarding against

**Comment by jthomaskerr** [comment]
Can't help but feel reminded of `rm -rf /$myNonexistentVariable` with this....

**Comment by tekumara** [comment]
I've added a filter to guard against empty names for all operations in #376
